### ISSUE TITLE
QR 제너레이션 할때 링크 에러 

### ISSUE THREAD

**Issue by heebinYoo** [KimGenius/Wemarket-web#1]
wemarket.kr:3000/customer?seller=48
이런식으로 포트번호가 들어감
컨피그에서 포트번호가 설정되어있는데 그 URL 그냥 가져다 쓰는 것 같다고 생각함.

**Comment by KimGenius** [comment]
prodHost 생성하여 해결
https://github.com/KimGenius/Wemarket-web/commit/edcc1951e95ddcd6a094b612b2f9070a27d1f5e1
