### ISSUE TITLE
커스터머 전화 오류

### ISSUE THREAD

**Issue by heebinYoo** [KimGenius/Wemarket-web#5]
커스터머에서 전화 버튼 누르면 텅 빔
![kakaotalk_photo_2018-11-17-18-21-00](https://user-images.githubusercontent.com/10597530/48659513-8e1b9880-ea95-11e8-8240-522aab922e0d.jpeg)
그리고 
![image](https://user-images.githubusercontent.com/10597530/48659514-983d9700-ea95-11e8-9f04-806459b2d3b0.png)
전화기 깨짐

**Comment by KimGenius** [comment]
https://github.com/KimGenius/Wemarket-web/commit/8a2872e55ee4e7a80275160ada3a93a00d5da402
