### ISSUE TITLE
주문내역 문제

### ISSUE THREAD

**Issue by heebinYoo** [KimGenius/Wemarket-web#6]
주문내역 몇번 새로고침해야 뜨더라

완료하기 버튼이 전역이였으면 좋겠다.
=> 완료하기만 누르기 하면 좀 좁은듯?
![image](https://user-images.githubusercontent.com/10597530/48659528-c7ec9f00-ea95-11e8-966b-1500d0761725.png)
들린다.

**Comment by heebinYoo** [comment]
최신순으로 띄워주게 쿼리 바꾸는게 좋을듯

**Comment by KimGenius** [comment]
전역이면 스크롤 하다가 잘못 누를 경우도 생길 수 있어서 부분만

**Comment by KimGenius** [comment]
https://github.com/KimGenius/Wemarket-server/commit/babcd67d559cfdc36278d89fe3d7231eae5a6e36
최신순 처리 완료
