### ISSUE TITLE
파트너스 더보기

### ISSUE THREAD

**Issue by heebinYoo** [KimGenius/Wemarket-web#9]
![image](https://user-images.githubusercontent.com/10597530/48659623-37af5980-ea97-11e8-9069-c0ee1a964a63.png)
![image](https://user-images.githubusercontent.com/10597530/48659625-3aaa4a00-ea97-11e8-89e2-c1e29e333e47.png)

더보기 버튼이 없는데?

**Comment by heebinYoo** [comment]
그리고 뭔가 비율 안맞는듯 맥에서

**Comment by KimGenius** [comment]
더보기 꼭 필요하면 추가하는걸로
